name: "Top up ASR pools"
description: "Runs the ASR pools top-up script for a specified period"

inputs:
  period-in-minutes:
    description: "The period for the top-up (in minutes)"
    required: true
  dryrun:
    description: "Dry run (0 - false, 1 - true)"
    required: false
    default: "0"
  debug-log:
    description: "Debug log (0 - false, 1 - true)"
    required: false
    default: "0"
  rpc-url:
    description: "RPC URL for blockchain connection"
    required: true
  pool-configs:
    description: "Pool configurations"
    required: true
  webhook-url:
    description: "Webhook URL for notifications"
    required: false
  sol-balance-warning-threshold:
    description: "SOL balance warning threshold"
    required: false

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Run top up ASR pools
      shell: bash
      env:
        RPC_URL: ${{ inputs.rpc-url }}
        POOL_CONFIGS: ${{ inputs.pool-configs }}
        DRY_RUN: ${{ inputs.dryrun }}
        DEBUG_LOG: ${{ inputs.debug-log }}
        PERIOD_IN_MINUTES: ${{ inputs.period-in-minutes }}
        SOL_BALANCE_WARNING_THRESHOLD: ${{ inputs.sol-balance-warning-threshold }}
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: pnpm run start

    - name: Save result CSV
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: /tmp/result.csv
        retention-days: 30
