name: Top up ASR pools every 15 minutes

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'

  push:
    tags:
      - trigger-fifteen-minutes**

  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Dry run (0 - false, 1 - true)'
        required: true
        default: '0'

jobs:
  run:
    name: Run top up ASR pools
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4

      - name: Top up ASR pools
        uses: ./.github/actions/top-up-asr-pools/
        with:
          period-in-minutes: '15' # 15 minutes
          dryrun: ${{ github.event_name == 'schedule' && '0' || github.event.inputs.dryrun }}
          debug-log: ${{ vars.DEBUG_LOG }}
          rpc-url: ${{ secrets.RPC_URL }}
          pool-configs: ${{ secrets.POOL_CONFIGS }}
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          sol-balance-warning-threshold: ${{ vars.SOL_BALANCE_WARNING_THRESHOLD }}
