name: Top up ASR pools daily

on:
  schedule:
    # Runs every day at 02:23 UTC to avoid peak usage hours
    - cron: '23 2 * * *'

  push:
    tags:
      - trigger-daily**

  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Dry run (0 - false, 1 - true)'
        required: true
        default: '0'

jobs:
  run:
    name: Run top up ASR pools
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4

      - name: Top up ASR pools
        uses: ./.github/actions/top-up-asr-pools/
        with:
          period-in-minutes: '1440' # 1 day
          dryrun: ${{ github.event_name == 'schedule' && '0' || github.event.inputs.dryrun }}
          debug-log: ${{ vars.DEBUG_LOG }}
          rpc-url: ${{ secrets.RPC_URL }}
          pool-configs: ${{ secrets.POOL_CONFIGS }}
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          sol-balance-warning-threshold: ${{ vars.SOL_BALANCE_WARNING_THRESHOLD }}
